### ISSUE TITLE
Use installers for Ruckstack CLI installation, not tgz/zip files

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#1]
For windows, generate an MSI and for Linux generate rpm and apt files.

This will allow easier and smarter installation and upgrades

**Comment by jameswmcnab** [comment]
If #37 doesn't happen I don't think you need this. Most all tools in the container ecosystem seem to be distributed directly as binaries, simply download and make executable. For example [`k3sup`](https://github.com/alexellis/k3sup):

```shell
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/

k3sup --help
```

In terms of updates could `ruckstack` check a URL for a more recent release and prompt the user to updae (every x executions)? That sort of thing seems to be a common pattern as well.

**Comment by nvoxland** [comment]
The trouble is that we need more than just executable. We have things like the example project files and other resource file we need, and while we can bundle that into the executable it has been a pain to manage in Go. A more traditional application directory structure would be much easier to deal with, but that would require an installer to manage.

**Comment by jameswmcnab** [comment]
Right yeah I see how that complicates things. In light I think releasing the builder in a container image (#37) is looking like more of the right choice 👍

**Comment by nvoxland** [comment]
With the new always-docker approach, this shouldn't be needed anymore
