### ISSUE TITLE
CLI: Use buildah for building images

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#36]
Currently, the builder makes calls out to docker to build images.

There are a few disadvantages with this:
- Requires a complex-to-install 3rd party dependency
- Requires a separate daemon to be running
- Makes running builder inside a docker container (build servers, etc.) more difficult
- Build hangs around in the general docker cache
- Calling out to a separate process makes error handling more difficult

Requirements for better solution:
- Simpler to install and manage than docker
- Ideally something that can be ran as a library within ruckstack
- Limited (ideally no) external dependencies
- Able to run in Docker containers
- Able to run in windows, mac, and linux 
- Able to run rootless
- Able to pull base images from custom and authenticated repositories

For the cross platform support, I'm entertaining the idea of shifting ruckstack to be a purely container-delivered software. That doesn't get us away from docker (unless we do an embedded containerd (still not windows) or runc/runsh setup), but it is a more "normal" docker setup. (#37)

**Possible Solutions**

_Buildah_

With buildah.io, we can build without docker. It can even be embedded as a library.

However, spending a couple days of research found:
- It only works on Linux (even when embedded)
- Even on linux, it needs 3rd party libraries installed (even when embedded)
- When things go wrong, the error messages are confusing because of apparent conflicts with cobra

_BuildKit_

To Look Into

_Img_

To Look Into

**Comment by nvoxland** [comment]
For reference, this was the test function I had. I would successfully build a tar file:

```
func main() {
	if buildah.InitReexec() {
		return
	}
	unshare.MaybeReexecUsingUserNamespace(false)

	buildStoreOptions, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
	util.Check(err)

	buildStore, err := storage.GetStore(buildStoreOptions)
	util.Check(err)

	opts := buildah.BuilderOptions{
		FromImage:        "docker.io/node:12-alpine",
		Isolation:        buildah.IsolationChroot,
		ReportWriter: os.Stdout,

		CommonBuildOpts:  &buildah.CommonBuildOptions{},
		ConfigureNetwork: buildah.NetworkDefault,
		SystemContext: 	  &types.SystemContext {
			SystemRegistriesConfPath: "/tmp/test.conf",
		},
	}

	builder, err := buildah.NewBuilder(context.TODO(), buildStore, opts)

	util.Check(err)
	builder.SetCmd([]string{"node", "/home/node/script.js"})

	util.Check(err)

	imageRef, err := archive.Transport.ParseReference("/tmp/test.out:test-me")

	util.Check(err)
	imageId, _, _, err := builder.Commit(context.TODO(), imageRef, buildah.CommitOptions{
		ReportWriter: os.Stdout,
	})

	util.Check(err)
	fmt.Printf("Image built! %s\n", imageId)

}
```

**Comment by nvoxland** [comment]
This is probably a no-go, but documenting it for my future interest and/or to see if anyone else has ideas.

**Comment by frezbo** [comment]
Tried buildkit or img

**Comment by nvoxland** [comment]
I looked at buildkit a bit, but off hand it felt maybe too low level? I've not seen https://github.com/genuinetools/img but that could be interesting.

The real goal of this ticket is "make the image build process better", with buildah just a possible option. I'll update the ticket description to better match that.

**Comment by frezbo** [comment]
img is basically `buildkit` but with a better UX and rootless support so that it works on on normal k8s pods without any extra privileges.

**Comment by nvoxland** [comment]
Thanks. I think the rootless support is a big part of what we need. Take a look at the updated description and LMK what you think

**Comment by nvoxland** [comment]
After playing with buildkit and buildah a bit, I decided it was best to stick with the standard docker process since that will integrate better with other images the user has on their system. Even if it's not rootless.

If it gets to be a problem, we can revisit it.
