### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by jameswmcnab** [ruckstack/ruckstack#39]
Hello!

Firstly this looks like a really interesting project. I've wanted something like this for a long time but I haven't had the time or knowledge to build it myself. My company current builds installers but we install our software and dependencies directly onto the host and I am longing to move to a containerised environment!

I wanted to get stuck in with this but I run on MacOS and there isn't a build for that. I'm a bit of a Go newbie, would a MacOS build be simple enough to add? I think there might be some value in it to the project generally due to the amount of devs that use a Mac.

Happy to contribute this if you think it would be good for the project (and I can figure it out!). I'm guessing the starting point would be to create a version of `BUILD.sh` with `GOOS=darwin`?

**Comment by jameswmcnab** [comment]
Realised this might be moot if #37 is done

**Comment by nvoxland** [comment]
Hi, great to hear you find the project interesting, @jameswmcnab and appreciate any help and feedback you can.

Yes, like you mention, #37 sort of makes it moot but also sort of not. You are on the right path with adding the GOOS=darwin. That is mostly what needs to be done. 

I've been working hard on the "dockerize" PR #38 which has turned into as much of a "refactor and clean up the code in preparation for a 1.0 release" effort as anything.

I do have the "distribute it in docker" working in that branch, but I'm still on the fence on whether it is a good idea or not. I'd like to hear your thoughts on the idea in #37

**Comment by jameswmcnab** [comment]
Thanks @nvoxland. I've put some thoughts in #37.

**Comment by nvoxland** [comment]
The work I did for #37 will include a mac builder in 0.9.0
