### ISSUE TITLE
Preserve custom system-control name

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#49]
I had originally added in a custom name for "system-control" so the actual, installed version was something else. 

I wasn't sure how much people actually care for a custom name, and it complicates documentation so temporarily took it out.

There was enough interest and value to keeping it custom vs. generic that we should make sure it remains in for 0.9.0

**Comment by nvoxland** [comment]
Removed

**Comment by jameswmcnab** [comment]
I liked this feature as it allows for an additional level of branding for end users, but if its a pain to support then I understand taking it out.

**Comment by nvoxland** [comment]
Thanks for the feedback. It's not a huge pain, more that I made big changes to how the installer code was structured and had to at least temporarily take it out so left it out. 

It seemed like a useful for that reason, but I wanted some additional validation before going through the work of putting it back in.

Honestly, the biggest struggle has been in the docs. On doc pages like https://ruckstack.org/docs/server/status I say `The system-control status command...` but that "system-control" command doesn't actually exist for people. I had a note on https://ruckstack.org/docs/server/start but its unlikely people would see that first. I can add that note to every page that references system-control, but I'm not sure that is the best option. 

Any suggestions?

**Comment by jameswmcnab** [comment]
I see where you are coming from on the documentation front. I didn't experience confusion when I was following the docs myself, but I can see there is scope for that. The solution of the note that mentions the name may be customised covers this concern in my opinion.

My use cases for preferring a custom name here is:

1. As mentioned for branding purposes, especially as I'd probably create a symlink to `/usr/local/bin` or similar to allow end users to enter the command without the entire path (thereby loosing the context of the project name in the path).

2. `system-control` is a bit close to both `sysctl` and `systemctl` for my liking when referring to the command with my team and similarly experienced end users.

**Comment by nvoxland** [comment]
Very good point on system-control vs sysctl and systemctl. I was trying to go with a generic name but others have already taken it...


I'll go back to the custom name and try something like `<control> status` or something in the docs

**Comment by nvoxland** [comment]
Functionality is restored in main for 0.9.0
