### ISSUE TITLE
Do not ship 3rd party binaries and images

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#62]
In 0.9.0, we included the airgap-images.tar plus the k3s and helm binaries. While it was nice to save the download time after install, it makes the ruckstack download much larger and requires users to basically re-download those images when upgrading Ruckstack, even if they don't have to be uploaded.

To keep the downloads more streamlined, we're taking the extra images out of 0.10.0. The biggest impact will be people using ruckstack without direct internet access. I'm not sure how common that is, and if it's a problem we can find other solutions to that.

**Comment by jameswmcnab** [comment]
One of my requirements is being able to run installers/upgrades on air-gapped systems. I think this would break that?

Pretty niche perhaps but I wonder how important that is to other vendors looking for a solution like ruckstack.

Would it be possible to make this optional via a build time flag?
