### ISSUE TITLE
Use appimage for packaging

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#84]
Is https://appimage.org/ better than our custom packaging?

**Comment by jameswmcnab** [comment]
Is AppImage not just for desktop applications?

**Comment by nvoxland** [comment]
I had seen a reference to it but hadn't looked into it yet. Made this ticket as a reminder to look.

It probably doesn't just have to be for desktop applications, but apparently it is much more of a binary container than the installer I was thinking it was. I thought it would maybe be an alternative to the custom installer I wrote, but apparently needed to spend more than 5 seconds reading their site :)
