### ISSUE TITLE
Support CRDs

### ISSUE THREAD

**Issue by vhdirk** [ruckstack/ruckstack#89]
I was trying to bundle https://enmasseproject.github.io/, but it seems to fail when it encounters a CRD, which is defined in one of the first manifests I give it.
See example project here: https://github.com/vhdirk/ruckstack-enmasse

Is this intended behaviour? How do you deal with CRDs?

**Comment by nvoxland** [comment]
I'll take a look. Thanks for the example project, that is very helpful

**Comment by nvoxland** [comment]
Should be fixed. Can you try the latest build from https://github.com/ruckstack/ruckstack/actions?query=branch%3Amain and let me know if you run into any other troubles?
